INSERT INTO public.editeur (id, nom_maison_edition) VALUES (1, 'Hachette');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (2, 'Flammarion');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (3, 'Bayard');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (4, 'Gallimard');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (5, 'Albin Michel');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (6, 'Actes Sud');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (7, 'Eyrolles');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (8, 'Les Editions de Minuit');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (9, 'Belin');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (10, 'Larousse');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (11, 'JC Lattès');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (12, 'Seuil');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (13, 'Grasset');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (14, 'PLON');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (15, 'Stock');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (16, 'Fayard');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (17, 'Nathan');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (18, 'Presses Universitaires de France');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (19, 'Folio');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (20, 'Le Livre de Poche');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (21, 'J''ai Lu');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (22, '10X18');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (23, 'Robert Laffont');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (24, 'Penguin Classics');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (25, 'New Edition');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (26, 'Point');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (27, 'Rivages/Noir');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (28, 'Pocket');
INSERT INTO public.editeur (id, nom_maison_edition) VALUES (29, 'Seuil');

